config/routes.rb
HotelsApp::Application.routes.draw do
 
  resources :users
  resources :hotels do 
  resources :rooms
  end
resources :sessions, only: [:new, :create, :destroy]

 root to: 'static_pages#home'
  
 match '/hotels',  to: 'hotels#index'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible :city, :country, :state, :street
  belongs_to :hotel
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  attr_accessible :star_rating, :rates_count, :title, :hphoto
  mount_uploader :hphoto, HphotoUploader
  has_one  :address
  has_many :user_hotels
  has_many :rooms
  has_many :users, through: :user_hotels
  	validates	:title, presence: true, 
			 	length: { maximum: 50 },	
			 	uniqueness: {case_sensitive: false} 

	validates :star_rating, presence: true
	validates :rates_count, presence: true
	
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :link, :room_id
end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :hotel_id, :price, :room_type, :room_number, :breakfast_included, :photo
  mount_uploader :photo, PhotoUploader
  belongs_to :hotel
  #has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" },
  # :default_url => "/images/:style/missing.png",
  # :path => ":rails_root/public/:style/:id/:basename.:extension"
end

app/models/user.rb
class User < ActiveRecord::Base
attr_accessible :name, :email, :password, :password_confirmation

has_secure_password
has_many :user_hotels
  has_many :hotels, through: :user_hotels

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

 validates :name, 	presence: true, 
 					length: { maximum: 50 }
 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 validates :email, 	presence: true, 
 					format: { with: VALID_EMAIL_REGEX },
 					uniqueness: {case_sensitive: false}
 validates :password, 	presence: true,
					 	length: { minimum: 6 }
 validates :password_confirmation, presence: true
 private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
 		end

app/models/user_hotel.rb
class UserHotel < ActiveRecord::Base
  attr_accessible :comment, :rating, :user_id, :hotel_id
  belongs_to :user
  belongs_to :hotel
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def index
    
    @hotels = Hotel.order('star_rating/rates_count DESC')
    @hotelsordered = @hotels.limit(5)
    @otherhotels = @hotels.reverse[0..(@hotels.count - 6)].sort_by{|h| h.title}
    
  end

  def show
    @hotel = Hotel.find(params[:id])
    #This piece of code was created to have commas between
    #address parts and don't have it at the end of line as 
    #it would be using simple loop in view
   @address_attr = Address.find_by_hotel_id(params[:id])
   @address2 = []
     if !@address_attr.nil? then 
                      @address_t = {"country" => @address_attr.attributes['country'],
                "state" => @address_attr.attributes['state'],
                "city" => @address_attr.attributes['city'],
                "street" => @address_attr.attributes['street'] }
    
    @address_t.each do  |a,b|  
      if !b.blank? then @address2.push(b)
      end
        end
      @address = @address2.join(", ")
    end
      ############################
      # I didnt know how to organize correctly many-to-many connection,
      # so decided to save UserHotel separately from 
  @userhotel = UserHotel.find_all_by_hotel_id(params[:id])
  @curruserhotel = UserHotel.find_by_hotel_id_and_user_id(params[:id],current_user.id)
   #used for having less code in view
   @rating = !@curruserhotel.nil? ? @curruserhotel[:rating] : 0
  
  
end
 

  def new
    @hotel = Hotel.new
    @address = Address.new
    @userhotel = UserHotel.new
  end

  def create

    @hotel = Hotel.new(params[:hotel].merge(:star_rating => params[:user_hotel][:rating], :rates_count => 1))
    @hotel.address = Address.new(params[:address])
    @hotel.hphoto = params[:hotel][:hphoto]
      
  if @hotel.save
    @user_hotel = UserHotel.new(params[:user_hotel].merge(:hotel_id => @hotel[:id], :user_id => current_user.id))
    @user_hotel.save
    
    flash[:success] = "New hotel was added. Thank you"
    redirect_to @hotel
  else
    render :action => 'new'
  end
end

def edit
  @hotel = Hotel.find(params[:id])

  @userhotel = UserHotel.find_by_hotel_id_and_user_id(params[:id], current_user.id)
  if !@userhotel.blank?  then                     
                       @mark = @userhotel[:rating] end
  @address = Address.find_by_hotel_id(params[:id])
  
end

def update 

  @hotel = Hotel.find(params[:id])
  
@userhotel = UserHotel.find_by_hotel_id_and_user_id(params[:id], current_user.id)
@hotel.star_rating += (params[:radiobutton]).to_i
@hotel.address = Address.find_by_hotel_id(params[:id])
if !@userhotel.blank?
 @hotel.star_rating -= (@userhotel[:rating]).to_i
else
 @userhotel = UserHotel.new(:rating => params[:radiobutton].to_i, :hotel_id => params[:id], :user_id => current_user.id, :comment => params[:user_hotel][:comment])
end

  if (@hotel.update_attributes(:title => params[:hotel][:title], :star_rating => @hotel.star_rating, :hphoto => params[:hotel][:hphoto]) 
     @hotel.address.update_attributes(params[:address])
  @userhotel.update_attributes(:rating => params[:radiobutton].to_i, :hotel_id => params[:id], :user_id => current_user.id, :comment => params[:user_hotel][:comment]))

    flash[:success] = "Information updated"
    redirect_to @hotel
  else
    @hotel.star_rating += @user_hotel.rating
    render 'edit'
  end
end



end

app/controllers/rooms_controller.rb
 class RoomsController < ApplicationController

def index
    @room = Room.find_all_by_hotel_id(params[:hotel_id])
    @roomSortedByPrice = @room.sort_by{ |k| k["price"] }.reverse
    
    
  end

 def show
    @room = Room.find(params[:id])
  end

  def new
  	@room = Room.new
  end

  def create
   @newroomid = Room.find_all_by_hotel_id(params[:hotel_id]).count + 1
    @room = Room.new(params[:room].merge(:hotel_id => params[:hotel_id], :room_number => @newroomid) )
    @room.photo = params[:file]
    if @room.save
    	flash[:success] = "New room was added"
      redirect_to hotel_room_path(params[:hotel_id], @room.id)
    else
      render 'new'
    end
  end

  #def destroy
  #  redirect_to root_url
  #end

  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
    	sign_in @user
      flash[:success] = "Welcome to the Hotels Application!"
      redirect_to @user
    else
      render 'new'
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Hotels App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def user_by_user_id(user_hotel)
		User.find(user_hotel.user_id).name
	end
end

app/views/hotels/edit.html.erb
<script type="text/javascript" src="http://domovoy063.nxt.ru/jquery-1.4.2.min.js"></script>
<script type="text/javascript">
  $(document).ready(function(){
    $('.splLink').click(function(){
      $(this).parent().children('div.splCont').toggle('normal');
      if( $(this).attr("value")=='Hide' ) $(this).attr("value","Закрыть");
      else $(this).attr("value","Edit address");
      return false;
    });
  });
</script>

<%= form_tag(hotel_path(@hotel), {:multipart => true, method: :PUT}) do %>

  
  <p>
    <%= label :hotel, :title %>
    <%= text_field :hotel, :title %>
  </p>
  <fieldset>
  <p class="some-class">
    <p>Mark:</p>
    <% (1..5).each do |i| %>
    <% if @mark == i then %>
<%=label :user_hotel,  i, {style: "margin-left:15px; margin-right:-15px"} %>
<%= radio_button_tag(:radiobutton, i, :checked => "checked")  %>
<% else %>
<%=label :user_hotel,  i, {style: "margin-left:15px; margin-right:-15px"} %>
<%= radio_button_tag(:radiobutton , i) %>
      <% end end %>   
 </p>
</fieldset>
<p>

  <%= file_field :hotel, :hphoto %>

</p>

    <div><input class="splLink" type="button" value="Edit address"><div class="splCont">

    <p>
    <%= label  :address, :country %><br>
    <%= text_field :address, :country, value: @address[:country]%>
  </p>
   <p>
    <%= label  :address, :state %><br>
    <%= text_field :address, :state, value: @address[:state]%>
  </p>
   <p>
    <%= label  :address, :city %><br>
    <%= text_field :address, :city, value: @address[:city]%>
  </p>
   <p>
    <%= label :hotel, :address, :street %><br>
    <%= text_field :address, :street, value: @address[:street]%>
  </p>
  
    </div></div>
    <br>
    <p>
    <%= label :user_hotel, :comment %>
    <%= text_area :user_hotel, :comment, 
     {value: @userhotel[:comment], rows:"4", cols: "50"}%>
  </p>
  <br>

 
<!-- hidden_field_tag :model_id, params[:model_id] -->

 
  <p>
  <%= submit_tag 'Update' , class: "btn btn-large btn-primary" %>
  </p>
<% end %>
 
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
<% provide(:title, "Hotels") %>
<div style = "margin-left:30px">
  
      <h2>

      	Best five hotels
</h2>       

      	<%  @hotelsordered.each do |h|  %>
        <div style = "float:left; margin-bottom:20px;">
           <div style = "height:150px; width:300px;">
      	     <%= link_to image_tag(h.hphoto_url(:thumb)), 
             hotel_path(h.id) %>
           </div>
           <%= h.title %> 
           (<%= (h.star_rating/h.rates_count).round(2) %>)
      	</div>
      	<% end %>
      
</div>

</div>
<div><p>Other hotels (in alphabetic)</p>
      <%  @otherhotels.each do |h|  %>
      <%= link_to h.title, 
             hotel_path(h.id) %>
      (<%= (h.star_rating/h.rates_count).round(2) %>)
             <% end %>
     </div>
     <div>
      <%= link_to "Add new hotel", 
             new_hotel_path %>
      
     </div>

app/views/hotels/new.html.erb
<% provide(:title, 'New hotel') %>
<h1>Add a hotel</h1>

<div class="row">
  <div class="span6 offset3">


<%= form_tag(hotels_path, :multipart => true) do %>

<div style ="width:500px; height:35px">
  
  Hotel title (necessary):


<%= text_field :hotel, :title, :style => "float:right" %>
</div>
  
  

<div>
  Rate this hotel (necessary):
  <%= text_field :user_hotel, :rating %>
</div>
<p>
  You can leave a short description
  <%= text_field :user_hotel, :comment %>
</p>
<p>
<%= file_field :hotel, :hphoto %>
</p>
Please fill in the address  
<p>
  Country:
  <%= text_field :address, :country %>
</p>
<p>
  State:
  <%= text_field :address, :state %>
</p>
<p>
  City:
  <%= text_field :address, :city %>
</p>
<p>
  Street:
  <%= text_field :address, :street %>
</p>

<p>
  <%= submit_tag 'Create' , class: "btn btn-large btn-primary" %>
</p>
<% end %>
<%= form_tag %>


  </div>
</div>

app/views/hotels/show.html.erb
<% provide(:title, @hotel.title) %>
<div>
 
    <section>
      <h1>
      	<%= @hotel.title %>
      </h1>
      	<h2>
          <p>Rating : <%=@hotel.star_rating/@hotel.rates_count%>
            (Your rating: <%=@rating%>)
          </p>
         <% if !@address.blank?     %>
      		<%=  "Address:" %>

      		<%= @address  %> 
		 	<%  else %>
		 <%= "No address, sorry " %>	
     			<%  end %>	
          	
		</h2>
    </section>
    <div style = "text-align:center">
    <%= image_tag(@hotel.hphoto_url) %>
      </div>
      <div style = "text-align:center">
      <p>
      <%= link_to "Click here", hotel_rooms_path(params[:id])%> to show rooms of this hotel
     </p> 
   </div>
      <br>
      <div style = "text-align:center">
    <div style = "text-align:center">
<% @userhotel.each do |u| if !u.comment.blank? then %>

<div>
  <br>
  <p class = "gray-small">
    <%= user_by_user_id(u) %> left this comment:
  </p>
  <p class = "bordered">
<%= u.comment %>
</p>
</div>
<%  else %>
<p class = "gray-small">
   No comments yet
  </p>
  <% end end %>
</div>
<br>
<br>
<div>
  <%= "If you want to change some information or add a comment you can do this " %>
      <%= link_to 'here:', edit_hotel_path(@hotel.id) %>
  <div>


</div>

      
 

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Developed by Oleg Trofimenko
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://isport.ua/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Hotels app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Hotels <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Hotels list", hotels_path%></li>
                <li><%= link_to "Add new hotel", new_hotel_path%></li>
              </ul>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user, 
                id: "profile" %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    </div>
  </body>
</html>

app/views/rooms/index.html.erb
<% provide(:title, "Rooms") %>

  
      <h3>
        <% if !@roomSortedByPrice.blank? %>
      	This hotel propose you these rooms.
        <% else %>
        Sorry, no rooms added yet
        <% end %>
        </h3>

        <div>
          <p>
            You can add a
            <%= link_to " new room ", 
            new_hotel_room_path(params[:hotel_id]) %> to this list
          </p>
        </div>
        


      	<%  @roomSortedByPrice.each do |r|  %>

        <div style = "float:left; margin-bottom:20px;">
          <div style = "height:150px; width:300px;">

        <%= link_to image_tag(r.photo_url(:thumb)), 
        hotel_room_path(params[:hotel_id], r.id) %>
        </div>
        
          <%= (r.room_number.to_s << "." << r.room_type << " - " <<
 r.price.to_s << "$ per day.") %>        
        
      </div>

    

        

      

      	
      	<% end %>
        </div>
      
     <%= link_to " Back to the hotel ", 
            hotel_path(params[:hotel_id]) %>
            <br>
  <%= link_to " Back to the hotels list ", 
            hotels_path %>

app/views/rooms/new.html.erb
<% provide(:title, 'New room') %>
<h1>Add some description</h1>

<div class="row">
  <div class="span6 offset3">
<%= form_for @room, :url => hotel_rooms_path,
 :html => {:multipart => true} do |f| %>
   


      <%= f.label :room_type %>
      <%= f.text_field :room_type %>

      <%= f.label :room, :price %>
      <%= f.text_field :price %>

      <p>
      Included breakfast 
      <%= f.check_box :breakfast_included %>
      </p>

      <%= f.file_field :photo %>
      <p></p>
      
     
      
      <%= submit_tag 'Add', class: "btn btn-large btn-primary" %>
   <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<% provide(:title, "Room N#{@room.room_number}") %>
<div >
  
    
      <h1>
      	<%= "Room N#{@room.room_number}" %>
      </h1>
      <%= image_tag @room.photo_url %>
	
	<br>
      Room type: <%= @room.room_type %>
      <br>
      Price: <%= @room.price %>
      <div>
  <%= link_to " Back to the rooms list ", 
            hotel_rooms_path(params[:hotel_id]) %>
            <br>
  <%= link_to " Back to the hotel ", 
            hotel_path(params[:hotel_id]) %>
            <br>
  <%= link_to " Back to the hotels list ", 
            hotels_path %>
    	</div>
</div>

app/views/shared/_error_messaged.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
    <h1>About Us</h1>
    <p>     
      It is simple hotels application.
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contacts is under construction
  
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
    <h1>Help</h1>
    <p>
      Get help
    </p>

app/views/static_pages/home.html.erb
<script type="text/JavaScript">
<!--
function timedRedirect(redirectTo, timeoutPeriod)
{
    setTimeout("location.href = redirectTo;",timeoutPeriod);
}
//-->
</script>
<div class="center hero-unit">
  <h1>Welcome to the Hotels App</h1>

  <h2>
  
    This is the home page for the
    hotels advisor application.
  </h2>
  <% if !current_user.blank? %>

<meta HTTP-EQUIV="REFRESH" content="10; url=<%= hotels_path %>">
You are already authenticated and will be redirected in 10 seconds to main page
 
<% else %>
 <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
 <% end %>
</div>

<%= link_to image_tag("rails.png", alt: "google"), 'http://google.com/' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
      	<%= @user.name %>
      </h1>
      </section>
  </aside>
</div>